# Generated by Django 4.1.7 on 2023-04-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
        ('base', '0004_rename_participant_room_participants'),
    ]

    operations = [
    ]
